---
title: P2-1
---

```{r}
library(recommenderlab)
library(dplyr)
library(tidyr)
library(ggplot2)
#100K data source #http://files.grouplens.org/datasets/movielens/ml-100k
movie<-read.table("http://files.grouplens.org/datasets/movielens/ml-100k/u.data")
colnames(movie)<-c("users","items","rating","timestamp")
users<-read.table("http://files.grouplens.org/datasets/movielens/ml-100k/u.user",sep="|")
colnames(users)<-c("userid","age","gender","occupation","zipcode")
item<-read.delim("http://files.grouplens.org/datasets/movielens/ml-100k/u.item",sep="|",header=F)
item<-item[,c(-1,-3,-4,-5)]
colnames(item)<-c("MovieName","unknown", "Action","Adventure","Animation","Children", "Comedy" ,"Crime" ,"Documentary","Drama","Fantasy","Film-Noir","Horror","Musical","Mystery","Romance","Sci-Fi","Thriller","War","Western")

```


```{r}
movie.r=movie[,1:3]
movie.new<-movie.r%>%spread(items,rating,fill=0)
movie.new=movie.new[,-1]
s100<-movie.new[100,]
item[which(s100>=4),1]
```
##Movies that this user(No.100) likes.


```{r}
movie100<-movie.new[,which(s100>=4)]
p=c()
for (i in 1:dim(movie100)[1]){
  a=movie100[i,]
  if(sum(as.numeric(a[which(a>=4)]))>=30){
    p=append(p,i)
  }
}
p=p[-which(p==100)]
movie.e100<-movie.new[p,]
n=c()
for (i in p){
  b=movie.new[i,]
  n=append(n,which(b>=4))
}
sort(table(n),decreasing = TRUE)[1:20]
item[c(313,258,272,302,300,315,316,328,286,269,50,307,333,750,100,347,751,288,294,237),1]
```
##Movies the silimar people like most.


```{r}
s100<-movie.new[100,]
movie.inf100=item[which(s100>=4),-1]
rec=item[c(313,258,272,302,300,315,316,328,286,269,50,307,333,750,100,347,751,288,294,237),]
m=as.matrix(movie.inf100)
l=c()
for (i in 1:dim(rec)[1]){
  if(max(m%*%as.numeric(rec[i,-1]))>=3){
    l=append(l,i)
  }
}
rec[l,1]
```
##Result combined with the similarity of movies.


```{r}
result=rec[setdiff(l,which(s100>0)) ,1]
result
```
##Remove the movies this user had watched before.